package config

import (
	"fmt"
	"hash/fnv"
	"os"
	"path/filepath"
	"strings"

	"github.com/otori-lab/otori-cli/internal/models"
)

// CowrieConfigTemplate is the template for cowrie.cfg
const CowrieConfigTemplate = `# Cowrie Configuration File
# Generated by Otori CLI
# Profile: %s

[honeypot]
hostname = %s
log_path = var/log/cowrie
download_path = var/lib/cowrie/downloads
contents_path = honeyfs
txtcmds_path = txtcmds
share_path = share/cowrie
state_path = var/lib/cowrie
etc_path = etc

[ssh]
enabled = true
listen_endpoints = tcp:2222:interface=0.0.0.0
version = SSH-2.0-OpenSSH_6.0p1 Debian-4+deb7u2

[telnet]
enabled = true
listen_endpoints = tcp:2223:interface=0.0.0.0

[output_jsonlog]
enabled = true
logfile = var/log/cowrie/cowrie.json

[output_textlog]
enabled = true
logfile = var/log/cowrie/cowrie.log
`

// UserDBTemplate is the default template for userdb.txt
const UserDBHeader = `# Cowrie User Database
# Generated by Otori CLI
# Format: username:uid:password
# Use * as wildcard, use ! to deny access
#
# Examples:
#   root:x:root       - Allow root with password "root"
#   admin:x:*         - Allow admin with any password
#   guest:x:!         - Deny all passwords for guest
#

`

// WriteCowrieConfig generates and writes cowrie.cfg for a profile
func WriteCowrieConfig(profileDir string, config *models.Config) error {
	content := fmt.Sprintf(CowrieConfigTemplate, config.ProfileName, config.ServerName)

	filename := filepath.Join(profileDir, "cowrie.cfg")
	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		return fmt.Errorf("error writing cowrie.cfg: %w", err)
	}

	return nil
}

// WriteUserDB generates and writes userdb.txt for a profile
func WriteUserDB(profileDir string, config *models.Config) error {
	var content strings.Builder
	content.WriteString(UserDBHeader)

	// Add users from config
	if len(config.Users) > 0 {
		for _, user := range config.Users {
			// Default: allow user with any password (wildcard)
			content.WriteString(fmt.Sprintf("%s:x:*\n", user))
		}
	} else {
		// Default users if none specified
		content.WriteString("root:x:*\n")
		content.WriteString("admin:x:*\n")
	}

	filename := filepath.Join(profileDir, "userdb.txt")
	if err := os.WriteFile(filename, []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("error writing userdb.txt: %w", err)
	}

	return nil
}

// DockerComposeTemplate is the template for docker-compose.yml with dynamic ports
const DockerComposeTemplate = `# Docker Compose for Cowrie Honeypot
# Generated by Otori CLI
# Profile: %s

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: otori-%s
    restart: unless-stopped
    ports:
      - "%d:2222"   # SSH (external:internal)
      - "%d:2223"   # Telnet (external:internal)
    volumes:
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
      - ./honeyfs:/cowrie/cowrie-git/honeyfs:ro
      - cowrie-logs:/cowrie/cowrie-git/var/log/cowrie
      - cowrie-downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads
    environment:
      - COWRIE_HOSTNAME=%s

volumes:
  cowrie-logs:
    name: otori-%s-logs
  cowrie-downloads:
    name: otori-%s-downloads
`

// GetPortsForProfile generates deterministic ports based on profile name
// This allows multiple honeypots to run simultaneously with different ports
func GetPortsForProfile(name string) (sshPort int, telnetPort int) {
	h := fnv.New32a()
	h.Write([]byte(name))
	hash := h.Sum32()
	// Port range: 20000-29999, with 5000 possible pairs
	// Ensure even number for SSH, telnet is SSH+1
	sshPort = 20000 + int(hash%5000)*2
	telnetPort = sshPort + 1
	return
}

// WriteDockerCompose generates and writes docker-compose.yml for a profile
func WriteDockerCompose(profileDir string, config *models.Config) error {
	sshPort, telnetPort := GetPortsForProfile(config.ProfileName)

	content := fmt.Sprintf(DockerComposeTemplate,
		config.ProfileName,
		config.ProfileName,
		sshPort,
		telnetPort,
		config.ServerName,
		config.ProfileName,
		config.ProfileName,
	)

	filename := filepath.Join(profileDir, "docker-compose.yml")
	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		return fmt.Errorf("error writing docker-compose.yml: %w", err)
	}

	return nil
}

// GetOtoriDir returns the otori config directory (~/.otori)
func GetOtoriDir() string {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ".otori"
	}
	return filepath.Join(homeDir, ".otori")
}

// CustomizeHoneyFS customizes the honeyfs with profile-specific data
// Note: The base honeyfs is already extracted by templates.Extract()
func CustomizeHoneyFS(profileDir string, config *models.Config) error {
	honeyfsDir := filepath.Join(profileDir, "honeyfs")

	// Verify honeyfs exists (should have been extracted by templates.Extract)
	if _, err := os.Stat(honeyfsDir); os.IsNotExist(err) {
		return fmt.Errorf("honeyfs not found at %s (template extraction may have failed)", honeyfsDir)
	}

	// Collect users
	users := config.Users
	if len(users) == 0 {
		users = []string{"root", "admin"}
	}

	// Append custom users to passwd
	passwdPath := filepath.Join(honeyfsDir, "etc", "passwd")
	if err := appendUsersToPasswd(passwdPath, users); err != nil {
		return fmt.Errorf("error updating passwd: %w", err)
	}

	// Append custom users to shadow
	shadowPath := filepath.Join(honeyfsDir, "etc", "shadow")
	if err := appendUsersToShadow(shadowPath, users); err != nil {
		return fmt.Errorf("error updating shadow: %w", err)
	}

	// Append custom users to group
	groupPath := filepath.Join(honeyfsDir, "etc", "group")
	if err := appendUsersToGroup(groupPath, users); err != nil {
		return fmt.Errorf("error updating group: %w", err)
	}

	// Update hostname
	hostnamePath := filepath.Join(honeyfsDir, "etc", "hostname")
	hostname := config.ServerName
	if hostname == "" {
		hostname = "svr04"
	}
	if err := os.WriteFile(hostnamePath, []byte(hostname+"\n"), 0644); err != nil {
		return fmt.Errorf("error updating hostname: %w", err)
	}

	// Create custom bait file
	shareDir := filepath.Join(honeyfsDir, "etc", "share")
	if err := os.MkdirAll(shareDir, 0755); err != nil {
		return fmt.Errorf("error creating share directory: %w", err)
	}
	secretContent := fmt.Sprintf(`# Confidential - Do Not Share
# Server: %s
DB_HOST=192.168.1.100
DB_USER=admin
DB_PASS=SuperSecret123!
API_KEY=sk-prod-xxxxxxxxxxxx
`, config.ServerName)
	if err := os.WriteFile(filepath.Join(shareDir, "secret.txt"), []byte(secretContent), 0644); err != nil {
		return fmt.Errorf("error writing secret.txt: %w", err)
	}

	return nil
}

// CustomizeIAProfile customizes the IA honeypot profile (dynamic port, container name)
func CustomizeIAProfile(profileDir string, config *models.Config) error {
	sshPort, _ := GetPortsForProfile(config.ProfileName)

	// Read docker-compose.yml extracted by templates
	composePath := filepath.Join(profileDir, "docker-compose.yml")
	content, err := os.ReadFile(composePath)
	if err != nil {
		return fmt.Errorf("error reading docker-compose.yml: %w", err)
	}

	// Replace default port with dynamic port
	newContent := strings.Replace(string(content),
		"2222:2222",
		fmt.Sprintf("%d:2222", sshPort), 1)

	// Replace container name (try all possible patterns)
	newContent = strings.Replace(newContent,
		"container_name: ssh-honeypot",
		fmt.Sprintf("container_name: otori-%s", config.ProfileName), 1)
	newContent = strings.Replace(newContent,
		"container_name: otori-ia",
		fmt.Sprintf("container_name: otori-%s", config.ProfileName), 1)
	newContent = strings.Replace(newContent,
		"container_name: honeypot-ia",
		fmt.Sprintf("container_name: otori-%s", config.ProfileName), 1)

	// Replace hostname in environment
	newContent = strings.Replace(newContent,
		`FAKE_HOSTNAME: "honeypot"`,
		fmt.Sprintf(`FAKE_HOSTNAME: "%s"`, config.ServerName), 1)

	return os.WriteFile(composePath, []byte(newContent), 0644)
}

// appendUsersToPasswd adds custom users to passwd file
func appendUsersToPasswd(path string, users []string) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	uid := 1000
	for _, user := range users {
		if user != "root" {
			line := fmt.Sprintf("%s:x:%d:%d:%s:/home/%s:/bin/bash\n",
				user, uid, uid, capitalize(user), user)
			if _, err := f.WriteString(line); err != nil {
				return err
			}
			uid++
		}
	}
	return nil
}

// appendUsersToShadow adds custom users to shadow file
func appendUsersToShadow(path string, users []string) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	for _, user := range users {
		if user != "root" {
			line := fmt.Sprintf("%s:*:15800:0:99999:7:::\n", user)
			if _, err := f.WriteString(line); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendUsersToGroup adds custom user groups to group file
func appendUsersToGroup(path string, users []string) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	gid := 1000
	for _, user := range users {
		if user != "root" {
			line := fmt.Sprintf("%s:x:%d:\n", user, gid)
			if _, err := f.WriteString(line); err != nil {
				return err
			}
			gid++
		}
	}
	return nil
}

// capitalize returns the string with first letter capitalized
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
